# Python for ML

#### Three powerful packages
1. numpy
2. pandas
3. mathplotlib
4. SkLearn

### numpy (Numerical Python)

- NumPy is a python library used for working with __arrays__.
- It also has functions for working in domain of __linear algebra, fourier transform, and matrices__.
- The array object in NumPy is called __ndarray__.

In [ ]:
import numpy

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)   #for check numpy version

1.18.1


In [ ]:
x = np.array([2,1,0])

In [ ]:
print(x)
print(type(x))
print(x.shape)
print(len(x))

[2 1 0]
<class 'numpy.ndarray'>
(3,)
3


In [ ]:
y=np.array([[1,2,3],[5,6,7]])
print(y)
print(type(y))
print(y.shape)
print(len(y))

[[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>
(2, 3)
2


In [ ]:
z= np.array([[1.+0.j, 2.+0.j],[0.+0.j, 3.+0.j]])
print(z)
print(type(z))
print(z.shape)
print(len(z))

[[1.+0.j 2.+0.j]
 [0.+0.j 3.+0.j]]
<class 'numpy.ndarray'>
(2, 2)
2


In [ ]:
y = np.array([[1,2],[3,4,5]])
print(y)
print(type(y))
print(y.shape)
print(len(y))

[list([1, 2]) list([3, 4, 5])]
<class 'numpy.ndarray'>
(2,)
2


C:\Users\JaFsi\anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


Checking the Data Type of an Array

In [ ]:
print(x.dtype)

int32


In [ ]:
print(y.dtype)

object


In [ ]:
print(z.dtype)

complex128


List of all data types in NumPy and the characters used to represent them.
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

Converting Data Type on Existing Arrays

In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Creating Arrays With a Defined Data Type

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


- For i, u, f, S and U we can define size as well.

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)


[1 2 3 4]
int32


__Copy and View__

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()


print(x)
print(x.base)
print(y)
print(y.base)

[1 2 3 4 5]
None
[1 2 3 4 5]
[1 2 3 4 5]


Check Number of Dimensions

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("a ---> ",a.ndim)
print("b ---> ",b.ndim)
print("c ---> ",c.ndim)
print("d ---> ",d.ndim)

a --->  0
b --->  1
c --->  2
d --->  3


#### Higher Dimensional Arrays
- An array can have any number of dimensions.
- When the array is created, you can define the number of dimensions by using the __ndmin__ argument.

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


- __Note__:To create an ndarray, we can pass a __list, tuple or any array-like object__ into the __array()__ method

In [ ]:
A = np.zeros((2,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
B = np.ones((2,3))
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
B = np.ones((2,3), dtype=int)
print(B)

[[1 1 1]
 [1 1 1]]


In [ ]:
C = np.eye(3)
print(C)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
D1 = np.arange(10)
print(D1)
D2 = np.arange(5,20)
print(D2)
D3 = np.arange(5,20,3)
print(D3)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  8 11 14 17]


In [ ]:
E = np.linspace(1,50,3)
print(E)

[ 1.  25.5 50. ]


In [ ]:
E = np.linspace(1,50,5)
print(E)

[ 1.   13.25 25.5  37.75 50.  ]


In [ ]:
F = np.random.random((3,4))
print(F)

[[0.16480877 0.88190235 0.96194541 0.09358806]
 [0.94664323 0.82635031 0.05391323 0.97497223]
 [0.31270661 0.27026618 0.6013896  0.91915922]]


In [ ]:
x = np.random.random((3,4))
print(x)
print(x.shape)

[[0.28421862 0.8726235  0.4800598  0.41356226]
 [0.668213   0.85880259 0.36868548 0.19211527]
 [0.61345138 0.01706695 0.00868459 0.30956688]]
(3, 4)


Reshape rray

In [ ]:
print(x.reshape(6,2))

[[0.28421862 0.8726235 ]
 [0.4800598  0.41356226]
 [0.668213   0.85880259]
 [0.36868548 0.19211527]
 [0.61345138 0.01706695]
 [0.00868459 0.30956688]]


In [ ]:
print(x.reshape(3,2,2))

[[[0.28421862 0.8726235 ]
  [0.4800598  0.41356226]]

 [[0.668213   0.85880259]
  [0.36868548 0.19211527]]

 [[0.61345138 0.01706695]
  [0.00868459 0.30956688]]]


Flattening the arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
x = np.arange(12)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


NumPy Array Indexing

In [ ]:
print(x[4])

4


In [ ]:
print("Last------>", x[-1])

Last------> 11


In [ ]:
x= x.reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(x[1,2])

print(x[1][2])

6
6


__Note__: There are a lot of functions for changing the shapes of arrays in numpy __flatten, ravel__ and also for rearranging the elements __rot90, flip, fliplr, flipud etc__.

NumPy Array Slicing
- We pass slice instead of index like this: __[start : end]__.

In [ ]:
Y=np.arange(1,26)
print(Y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [ ]:
print(Y[:10])

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(Y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
print(Y[10:15])

[11 12 13 14 15]


In [ ]:
print(Y[-5:])

[21 22 23 24 25]


In [ ]:
print(Y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


- We can also define the step, like this: __[start : end : step]__

In [ ]:
print(Y[::4])

[ 1  5  9 13 17 21 25]


In [ ]:
print(Y[2:23:3])

[ 3  6  9 12 15 18 21]


In [ ]:
Y = Y.reshape((5,5))
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


- Slicing 2-D Arrays ---> __[a:b:c,p:q:r]__

In [ ]:
print(Y[1:4,2:5])

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [ ]:
print(Y[1:4:2,2:5:2])

[[ 8 10]
 [18 20]]


In [ ]:
print(Y[2:4,1:4])

[[12 13 14]
 [17 18 19]]


In [ ]:
print(Y[:5,:4])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [ ]:
print(Y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [ ]:
print(Y[:,-1:])

[[ 5]
 [10]
 [15]
 [20]
 [25]]


In [ ]:
print(Y[:,-1])

[ 5 10 15 20 25]


In [ ]:
print(Y[:,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [ ]:
print(Y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [ ]:
A = np.arange(1,6)
B = np.arange(6,11)
print(A)
print(B)

[1 2 3 4 5]
[ 6  7  8  9 10]


**Element-wise Operations**

In [ ]:
print(A+B)
print(A-B)
print(B-A)

print(A*2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 2  4  6  8 10]


In [ ]:
print(A**2)

[ 1  4  9 16 25]


In [ ]:
print(A<3)

[ True  True False False False]


**Element-wise Operations:** Operations performed on each corresponding element of arrays.

**Broadcasting:** A method that allows NumPy to handle arrays of different shapes automatically during arithmetic operations.

**Vectorization** in NumPy refers to applying operations to entire arrays at once instead of using loops for element-wise operations.

This technique improves performance and readability by leveraging optimized low-level libraries.

In [ ]:
A = np.array([1, 2, 3])
B = np.array([[10], [20], [30]])
print(A)
print(B)

# Broadcasting happens here
result = A + B  # A is a 1D array (shape (3,)) and B is a 2D array (shape (3, 1))
print(result)

[1 2 3]
[[10]
 [20]
 [30]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
A = np.arange(4).reshape(2,2)
B = np.eye(2)
print(A)
print(B)

[[0 1]
 [2 3]]
[[1. 0.]
 [0. 1.]]


In [ ]:
print(A+B)

[[1. 1.]
 [2. 4.]]


In [ ]:
print(A*B)

[[0. 0.]
 [0. 3.]]


In [ ]:
print(np.dot(A,B))

[[0. 1.]
 [2. 3.]]


In [ ]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(x.sum())

45


In [ ]:
print(x.sum(axis=0))

[12 15 18]


In [ ]:
print(x.sum(axis=1))

[ 6 15 24]


In [ ]:
print(x.max())
print(x.max(axis=0))
print(x.max(axis=1))

9
[7 8 9]
[3 6 9]


In [ ]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
x = np.arange(4).reshape(2,2)
print(x)

[[0 1]
 [2 3]]


In [ ]:
y=np.linalg.inv(x) #Inverse of a matrix
print(y)

[[-1.5  0.5]
 [ 1.   0. ]]


In [ ]:
print(np.dot(x,y))

[[1. 0.]
 [0. 1.]]


NumPy Array Iterating

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
for x in np.nditer(arr) #The  nditer() is a helping function that can be used from very basic to very advanced iterations.
  print(x)

1
2
3
4
5
6
7
8
9


Iterating With Different Step Size

In [ ]:
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
4
6
7
9


In [ ]:
for x in np.nditer(arr[::2, :]):
  print(x)

1
2
3
7
8
9


In [ ]:
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


#### Joining NumPy Arrays
- In NumPy we join arrays by axes
-  If axis is not explicitly passed, it is taken as 0.

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.concatenate((x, y), axis=1)
print(z)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.concatenate((x, y), axis=0)
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.concatenate((x, y))
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


##### Joining Arrays Using Stack Functions
- Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.stack((x, y),axis=1)
print(z)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.stack((x, y),axis=0)
print(z)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.stack((x, y))
print(z)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stacking Along Rows

In [ ]:
z = np.hstack((x, y))
print(z)

[[1 2 5 6]
 [3 4 7 8]]


Stacking Along Column

In [ ]:
z = np.vstack((x, y))
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Stacking Along Height (depth)

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.dstack((x, y))
print(z)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


##### Splitting NumPy Arrays
- Joining merges multiple arrays into one and Splitting breaks one array into multiple

In [ ]:
# Create a 1D NumPy array
a = np.arange(1, 21)  # Creates an array: [1, 2, 3, ..., 20]

# Split the array into 8 parts
split_array = np.array_split(a, 8)

# Display the result
for i, arr in enumerate(split_array):
    print(f"Part {i+1}: {arr}")

Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]
Part 4: [10 11 12]
Part 5: [13 14]
Part 6: [15 16]
Part 7: [17 18]
Part 8: [19 20]


- hsplit()

In [ ]:
a = np.array([[1,2,3,1],[4,5,6,2],[7,8,9,3],[10,11,12,4]])
print(a)
print("Splited Array")
newarr = np.hsplit(a, 2)
print(newarr)

[[ 1  2  3  1]
 [ 4  5  6  2]
 [ 7  8  9  3]
 [10 11 12  4]]
Splited Array
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3,  1],
       [ 6,  2],
       [ 9,  3],
       [12,  4]])]


- vsplit()

In [ ]:
newarr = np.vsplit(a, 2)
print(newarr)

[array([[1, 2, 3, 1],
       [4, 5, 6, 2]]), array([[ 7,  8,  9,  3],
       [10, 11, 12,  4]])]


__Note__: dsplit only works on arrays of 3 or more dimensions

#### NumPy Searching Arrays
- You can search an array for a certain value, and return the indexes that get a match.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(a == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
x = np.where(a%2 == 0)      #position of even numbers
print(x)

(array([1, 3, 5, 6], dtype=int64),)


#### NumPy Sorting Arrays

- You can sort arrays of any data type:

In [ ]:
A = np.array([3, 2, 0, 1])
print(np.sort(A))

[0 1 2 3]


In [ ]:
print(A)

[3 2 0 1]


- __Note__: This method returns a copy of the array, leaving the original array unchanged.

In [ ]:
m = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(m))

[[2 3 4]
 [0 1 5]]


#### Filtering Arrays
- In NumPy, you filter an array using a boolean index list.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


Creating Filter Directly From Array

In [ ]:
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


🚀 Keep Exploring NumPy! 🔍

**Thank You**