In [2]:
#matrix operations
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# create a matrix using numpy
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [3]:
A.shape

(2, 2)

In [4]:
B = np.array([[5,6,9],[7,8,9],[9,10,15]])

In [5]:
print(B)

[[ 5  6  9]
 [ 7  8  9]
 [ 9 10 15]]


In [6]:
B.shape

(3, 3)

In [7]:
# crate a matrix of random numbers
C = np.random.rand(3,3)

In [9]:
print(C)    

[[0.3468151  0.2397592  0.24219207]
 [0.76041801 0.57190764 0.66340921]
 [0.7428347  0.1257346  0.42009585]]


In [14]:
# create a matrix of random integers

d = np.random.randint(0,100,(3,3))
print(d)
d.shape 

[[65 42 32]
 [ 8 31 27]
 [39 42 40]]


(3, 3)

In [19]:
# all the elements of a matrix is ones
E = np.ones((3,3),dtype=int)
print(E)
E.shape

[[1 1 1]
 [1 1 1]
 [1 1 1]]


(3, 3)

In [17]:
# all the elements of a matrix is zeros
F = np.zeros((3,3)) 
print(F)
F.shape

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


(3, 3)

In [18]:
# all the elements of a matrix is zeros
F = np.zeros((2,3)) 
print(F)
F.shape

[[0. 0. 0.]
 [0. 0. 0.]]


(2, 3)

In [28]:
# identity matrix
I = np.eye(3,3)
print(I)
I.shape 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


(3, 3)

In [31]:
# transpose of a matrix
g = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(g)
k = g.T
print(k)
h = np.transpose(g)
print(h)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
# matrix addition

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A + B
print(C)
print()

[[ 6  8]
 [10 12]]



In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.add(A,B)
print(A)
print(B)
print(C)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [12]:
# matrix subtraction
D = np.subtract(A,B)
print(D)

[[-4 -4]
 [-4 -4]]


In [13]:
# multiplication of two matrices
A = np.random.randint(0,10,(2,3))
B = np.random.randint(0,10,(3,2))
print(A)
print(B)    

[[1 0 1]
 [6 0 0]]
[[3 9]
 [7 2]
 [7 6]]


In [16]:
C = np.dot(A,B)
print(C)
C.shape

[[10 15]
 [18 54]]


(2, 2)