In [3]:
import pandas as pd
import tensorflow as tf 
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

2025-01-06 10:16:23.561293: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-06 10:16:23.648848: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-06 10:16:23.747678: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1736138783.838422  470373 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1736138783.863474  470373 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-06 10:16:24.049649: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [4]:
df = pd.read_csv('insurance_data.csv')

In [3]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [5]:
df.shape

(28, 3)

In [21]:
from re import X
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordibility']], df['bought_insurance'], test_size=0.2, random_state=25)


In [7]:
len(X_train)

22

In [20]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [9]:
X_train_scaled.head()

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1

In [53]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

/home/muhammed-shafeeh/AI_ML/Ai-and-Ml/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
W0000 00:00:1736142828.597493  470373 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [54]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [55]:
model.fit(X_train_scaled, y_train, epochs=5000)


Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 482ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy

In [23]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[0.7621956 ],
       [0.18184492],
       [0.0742349 ],
       [0.3580879 ],
       [0.7939333 ],
       [0.92078567]], dtype=float32)

In [24]:
y_test


2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [51]:
coef, intercept = model.get_weights()
coef, intercept

NameError: name 'model' is not defined

In [32]:
X_train_scaled.head()

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1

In [39]:
# nural network from scratch


def sigmoid(x):
    import math
    return 1 / (1 + math.exp(-x))

sigmoid(3)

0.9525741268224334

In [33]:
def prediction_function(age, affordability):
    weighted_sum = coef[0]*age + coef[1]*affordability + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)


/tmp/ipykernel_170309/1926367944.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.7621955387518495

In [34]:
prediction_function(.18, 1)

/tmp/ipykernel_170309/1926367944.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.18184492001835625

In [44]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(epsilon,i)for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon)for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-np.array(y_predicted_new)))
    
    

In [40]:
# sigmoid function for array
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [46]:
def gradient_descent(age, affordability,y_true, epochs, loss_threshold):
    # w1 w2 biaq
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    
    for i in range(epochs):
        wieghted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(wieghted_sum)
        loss = log_loss(y_true, y_predicted)
        
        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted - y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted - y_true))
        bias_d= np.mean(y_predicted-y_true)
        
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d
        
        
        print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
        
        if loss <= loss_threshold:
            break
        
    return w1, w2, bias

        

In [47]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordibility'], y_train, 1000, 0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, bias:-0.2122349122718517, loss:0.681264778737757
Epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, bias:-0.2977578997796538, loss:0.6591474252715025
Epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, bias:-0.3715094724003511, loss:0.6431523291301917
Epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, bias:-0.43506643026891584, loss:0.6316873063379158
Epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, bias:-0.48994490058938817, loss:0.623471707997592
Epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, bias:-0.5375299543522853, loss:0.6175321183044205
Epoch:7, w1:0.93047170420295, w2:0.7983920007454487, bias:-0.5790424270894963, loss:0.6131591858705934
Epoch:8, w1:0.9361540784567942, w2:0.7965748796787705, bias:-0.6155315088627655, loss:0.6098518179750948
Epoch:9, w1:0.9434791243557357, w2:0.7973647616854131, bia

(np.float64(5.051047623653049),
 np.float64(1.4569794548473887),
 np.float64(-2.9596534546250037))

In [48]:
coef, intercept


(array([[9.2022505],
        [1.7556683]], dtype=float32),
 array([-4.9159713], dtype=float32))

In [59]:
class myNNE:
    
    
    def __init__(self,learning_rate,epoch,loss_threshold):
        
        self.learning_rate = learning_rate
        self.epoch = epoch
        self.loss_threshold = loss_threshold
        
    
    # fit function to train the model
    def fit(self, X, Y):
        
        self.m, self.n = X.shape
        
        self.weights = np.ones(self.n)
        self.bias = 0
        
        self.X = X
        self.Y = Y
        
        # implementing gradient descent
        for i in range(self.epoch):
            self.update_weights()
            
            print(f'epoch:{i}, weight:{self.weights}, bias:{self.bias}, loss:{self.loss}')    
            
            if self.loss <= self.loss_threshold:
                break
            
    # cost function
    
        
        
    def update_weights(self):
        
        # calculate y_predicted
        weighted_sum = np.dot(self.X, self.weights) + self.bias
        y_predicted = 1 / (1 + np.exp(-weighted_sum))
        
        
        # calculate loss
        epsilon = 1e-15
        y_predicted_new = [max(epsilon,i)for i in y_predicted]
        y_predicted_new = [min(epsilon,i)for i in y_predicted_new]
        log_loss = -np.mean(self.Y*np.log(y_predicted_new)+(1-self.Y)*np.log(1-np.array(y_predicted_new)))
        
        self.loss = log_loss
        
       
        
        
        # derivaties
        dw = 1/self.m *(np.dot(self.X.T, (y_predicted - self.Y)))
        db = np.mean(y_predicted - self.Y)
        
        
        # updating weights
        self.weights -= self.learning_rate *dw
        self.bias -= self.learning_rate * db
            
    def predict(self, X):
        
        weighted_sum = np.dot(self.X, self.weights) + self.bias
        y_predicted = 1 / (1 + np.exp(-weighted_sum))
        
        return y_predicted
    
        
        
    

In [50]:
my_model = myNN(learning_rate=0.01, epoch=5000, loss_threshold=0.4631)
my_model.fit(X_train_scaled, y_train)

epoch:0, weight:[0.99949815 0.99896696], bias:-0.0022683735472737165, loss:0.7113403233723417
epoch:1, weight:[0.99899854 0.99793742], bias:-0.004531110245838688, loss:0.7106947453938027
epoch:2, weight:[0.99850116 0.99691136], bias:-0.006788217377105742, loss:0.7100526623879727
epoch:3, weight:[0.99800601 0.9958888 ], bias:-0.009039702278981612, loss:0.7094140604774263
epoch:4, weight:[0.99751308 0.99486972], bias:-0.011285572345427677, loss:0.7087789257803064
epoch:5, weight:[0.99702238 0.99385412], bias:-0.013525835026017508, loss:0.708147244410992
epoch:6, weight:[0.99653391 0.992842  ], bias:-0.015760497825493266, loss:0.7075190024807606
epoch:7, weight:[0.99604764 0.99183336], bias:-0.01798956830332102, loss:0.7068941860984489
epoch:8, weight:[0.9955636 0.9908282], bias:-0.020213054073245, loss:0.7062727813711064
epoch:9, weight:[0.99508177 0.9898265 ], bias:-0.022430962802840876, loss:0.7056547744046482
epoch:10, weight:[0.99460215 0.98882828], bias:-0.024643302213068055, loss:0

In [57]:
my_model = myNN(learning_rate=0.01, epoch=5000, loss_threshold=0.4631)
my_model.fit(X_train_scaled, y_train)


epoch:0, weight:[0.99949815 0.99896696], bias:-0.0022683735472737165, loss:0.7113403233723417
epoch:1, weight:[0.99899854 0.99793742], bias:-0.004531110245838688, loss:0.7106947453938027
epoch:2, weight:[0.99850116 0.99691136], bias:-0.006788217377105742, loss:0.7100526623879727
epoch:3, weight:[0.99800601 0.9958888 ], bias:-0.009039702278981612, loss:0.7094140604774263
epoch:4, weight:[0.99751308 0.99486972], bias:-0.011285572345427677, loss:0.7087789257803064
epoch:5, weight:[0.99702238 0.99385412], bias:-0.013525835026017508, loss:0.708147244410992
epoch:6, weight:[0.99653391 0.992842  ], bias:-0.015760497825493266, loss:0.7075190024807606
epoch:7, weight:[0.99604764 0.99183336], bias:-0.01798956830332102, loss:0.7068941860984489
epoch:8, weight:[0.9955636 0.9908282], bias:-0.020213054073245, loss:0.7062727813711064
epoch:9, weight:[0.99508177 0.9898265 ], bias:-0.022430962802840876, loss:0.7056547744046482
epoch:10, weight:[0.99460215 0.98882828], bias:-0.024643302213068055, loss:0

In [58]:
import numpy as np

class myNN:
    def __init__(self, learning_rate, epoch, loss_threshold):
        """
        Initialize the neural network model with learning rate, epochs, and loss threshold.
        """
        self.learning_rate = learning_rate
        self.epoch = epoch
        self.loss_threshold = loss_threshold
        self.loss = None  # Initialize loss attribute

    def fit(self, X, Y):
        """
        Train the neural network using gradient descent.
        
        Parameters:
            X (numpy.ndarray): Input features of shape (m, n).
            Y (numpy.ndarray): Target labels of shape (m,).
        """
        # Initialize parameters
        self.m, self.n = X.shape
        self.weights = np.ones(self.n)
        self.bias = 0

        self.X = X
        self.Y = Y

        # Gradient descent loop
        for i in range(self.epoch):
            self.update_weights()

            # Print progress
            print(f'Epoch: {i}, Weights: {self.weights}, Bias: {self.bias}, Loss: {self.loss}')

            # Early stopping condition
            if self.loss <= self.loss_threshold:
                print("Loss threshold reached. Stopping early.")
                break

    def update_weights(self):
        """
        Perform one step of gradient descent: compute gradients, update weights and bias.
        """
        # Calculate predictions
        weighted_sum = np.dot(self.X, self.weights) + self.bias
        y_predicted = 1 / (1 + np.exp(-weighted_sum))

        # Clip predictions to avoid log(0) errors
        epsilon = 1e-15
        y_predicted_clipped = np.clip(y_predicted, epsilon, 1 - epsilon)

        # Compute log loss
        self.loss = -np.mean(
            self.Y * np.log(y_predicted_clipped) + (1 - self.Y) * np.log(1 - y_predicted_clipped)
        )

        # Compute gradients
        dw = np.dot(self.X.T, (y_predicted - self.Y)) / self.m
        db = np.mean(y_predicted - self.Y)

        # Update weights and bias
        self.weights -= self.learning_rate * dw
        self.bias -= self.learning_rate * db

    def predict(self, X):
        """
        Predict probabilities using the trained model.
        
        Parameters:
            X (numpy.ndarray): Input features of shape (m, n).
        
        Returns:
            numpy.ndarray: Predicted probabilities of shape (m,).
        """
        weighted_sum = np.dot(X, self.weights) + self.bias
        y_predicted = 1 / (1 + np.exp(-weighted_sum))
        return y_predicted
