In [3]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])


In [4]:
def MAE(y_true, y_predicted):
    total_error = 0
    for yp,yt in zip(y_predicted,y_true):
        total_error += np.abs(yp - yt)
    print(total_error)
    MAE = total_error / len(y_true)
    return MAE
    
        

In [5]:
# call the function
MAE(y_predicted,y_true)

2.5


np.float64(0.5)

In [6]:
# using numpy for abs
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [7]:
# using numpy for abs
np.mean(np.abs(y_predicted - y_true))

np.float64(0.5)

In [8]:
epsilon = 1e-15 

In [9]:
y_predicted_new = [max(epsilon,i)for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [10]:
y_predicted_new = [min(i,1-epsilon)for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [11]:
np.log(y_predicted)

/tmp/ipykernel_65236/815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [12]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [20]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-np.array(y_predicted_new)))



np.float64(17.2696280766844)

In [21]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(epsilon,i)for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon)for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-np.array(y_predicted_new)))
    
    

In [1]:
log = log_loss(y_true, y_predicted)


NameError: name 'log_loss' is not defined